# Generated by Django 4.1.7 on 2023-05-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporation', 'Corporation')], default='individual', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
