# Generated by Django 4.1.7 on 2023-06-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_dashboard', '0005_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='dunkin_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
