# Generated by Django 4.1.7 on 2023-06-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_dashboard', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
